Repository GIFTERZ/2023-text-me, pull requests merged in 2022-12, with the labels that each got.

#12 Room 컴포넌트 구현 (#11)
  frontend/.yarn/cache/html-to-image-npm-1.10.9-668c589562-e46163d0da.zip
  frontend/.yarn/install-state.gz
  frontend/components/room/LettersContainer.tsx
  frontend/components/room/SaveContainer.tsx
  frontend/components/room/ShareContainer.tsx
  frontend/components/room/ShareModal.tsx
  frontend/mocks/data/letters.js
  frontend/mocks/handlers/letters.js
  frontend/mocks/servers.js
  frontend/mocks/workers.js
  frontend/package.json
  frontend/pages/[uid]/index.tsx
  frontend/pages/index.tsx
  frontend/stores/useLetters.ts
  frontend/types/index.ts
  frontend/yarn.lock
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#14 사진 선택 컴포넌트 구현(#7)
  frontend/pages/_app.tsx
  frontend/pages/preview-card-picture/index.tsx
  frontend/pages/select-card-picture/index.tsx
  frontend/stores/useCardPicture.ts
  frontend/tsconfig.json
  node_modules/.yarn-integrity
  yarn.lock
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#15 편지 보기 컴포넌트 구현 (#13)
  frontend/.yarn/cache/@babel-generator-npm-7.20.5-d08ff0a892-31c10d1e12.zip
  frontend/.yarn/cache/@babel-parser-npm-7.20.5-2b25154357-e8d514ce0a.zip
  frontend/.yarn/cache/@babel-traverse-npm-7.20.5-dc0e9498d7-c7fed46861.zip
  frontend/.yarn/cache/@babel-types-npm-7.20.5-3ee242b980-773f0a1ad9.zip
  frontend/.yarn/cache/@emotion-is-prop-valid-npm-1.2.0-332d343e3d-cc7a19850a.zip
  frontend/.yarn/cache/@emotion-memoize-npm-0.8.0-c5dd451828-c87bb110b8.zip
  frontend/.yarn/cache/@emotion-stylis-npm-0.8.5-3e9db8959f-67ff595844.zip
  frontend/.yarn/cache/@emotion-unitless-npm-0.7.5-14e1171640-f976e5345b.zip
  frontend/.yarn/cache/@types-hoist-non-react-statics-npm-3.3.1-c0081332b2-2c0778570d.zip
  frontend/.yarn/cache/@types-styled-components-npm-5.1.26-aabda06611-84f53b3101.zip
  frontend/.yarn/cache/babel-plugin-styled-components-npm-2.0.7-543710bd48-80b06b10db.zip
  frontend/.yarn/cache/babel-plugin-syntax-jsx-npm-6.18.0-fcf0a98a71-0c7ce5b81d.zip
  frontend/.yarn/cache/camelize-npm-1.0.1-d86ebe085a-91d8611d09.zip
  frontend/.yarn/cache/css-color-keywords-npm-1.0.0-fc176df58b-8f125e3ad4.zip
  frontend/.yarn/cache/css-to-react-native-npm-3.0.0-ab07d67d74-98a2e9d4fb.zip
  frontend/.yarn/cache/hoist-non-react-statics-npm-3.3.2-e7b709e6c1-b153827042.zip
  frontend/.yarn/cache/postcss-value-parser-npm-4.2.0-3cef602a6a-819ffab0c9.zip
  frontend/.yarn/cache/react-card-flip-npm-1.2.0-0a7f83b87f-b317477909.zip
  frontend/.yarn/cache/shallowequal-npm-1.1.0-6688d419cb-f4c1de0837.zip
  frontend/.yarn/cache/styled-components-npm-5.3.6-934fe4f344-68eac1e451.zip
  frontend/components/room/LetterView.tsx
  frontend/components/room/LetterViewContainer.tsx
  frontend/components/room/LettersContainer.tsx
  frontend/mocks/handlers/letters.js
  frontend/package.json
  frontend/pages/[uid]/index.tsx
  frontend/stores/useLetterView.ts
  frontend/stores/useRoomEnter.ts
  frontend/yarn.lock
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#20 마이페이지 컴포넌트 구현 (#18)
  frontend/components/mypage/NicknameContainer.tsx
  frontend/mocks/data/members.js
  frontend/mocks/handlers/members.js
  frontend/mocks/servers.js
  frontend/mocks/workers.js
  frontend/pages/index.tsx
  frontend/pages/mypage.tsx
  frontend/stores/useMembers.ts
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#10 멤버 회원가입 (#8)
  backend/text-me/build.gradle
  backend/text-me/src/main/java/domain/entity/BaseEntity.java
  backend/text-me/src/main/java/domain/member/controller/MemberController.java
  backend/text-me/src/main/java/domain/member/dto/request/SignUpRequest.java
  backend/text-me/src/main/java/domain/member/dto/response/UserResponse.java
  backend/text-me/src/main/java/domain/member/entity/Member.java
  backend/text-me/src/main/java/domain/member/entity/Password.java
  backend/text-me/src/main/java/domain/member/exception/EmailDuplicatedException.java
  backend/text-me/src/main/java/domain/member/repository/MemberRepository.java
  backend/text-me/src/main/java/domain/member/service/MemberService.java
  backend/text-me/src/main/java/error/ErrorCode.java
  backend/text-me/src/main/resources/application.properties
  backend/text-me/src/main/resources/application.yml
Labels: 백 🐻, 개발 🧑‍💻

#26 메인 페이지 디자인 (#25)
  frontend/components/main/RoomEnterForm.tsx
  frontend/pages/index.tsx
  frontend/public/static/fonts/style.css
  frontend/stores/useMembers.ts
  frontend/styles/components/Button.ts
  frontend/styles/components/Form.ts
  frontend/styles/components/Frame.ts
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#33 CI yml 파일 설정 (#32)
  backend/text-me/.github/workflows/deploy.yml
Labels: 우선순위 ⭐⭐, 백 🐻, 개발 🧑‍💻

#31 방 디자인 (#27)
  frontend/components/layout/Layout.tsx
  frontend/components/room/Background.tsx
  frontend/components/room/ButtonsContainer.tsx
  frontend/components/room/Letter.tsx
  frontend/components/room/LetterView.tsx
  frontend/components/room/LetterViewContainer.tsx
  frontend/components/room/LetterViewMove.tsx
  frontend/components/room/LettersContainer.tsx
  frontend/components/room/SaveContainer.tsx
  frontend/components/room/SaveModal.tsx
  frontend/components/room/ShareContainer.tsx
  frontend/components/room/icons/MenuIcon.tsx
  frontend/components/room/icons/PlusIcon.tsx
  frontend/components/room/icons/SaveIcon.tsx
  frontend/components/room/icons/ShareIcon.tsx
  frontend/pages/[uid]/index.tsx
  frontend/pages/_app.tsx
  frontend/pages/index.tsx
  frontend/public/static/images/room-background.png
  frontend/styles/components/Button.ts
  frontend/styles/components/Form.ts
  frontend/styles/components/Frame.ts
  frontend/styles/components/Modal.ts
  frontend/styles/theme/Theme.ts
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#36 토큰 재발급 API 구현 (#23)
  .idea/jpa-buddy.xml
  backend/text-me/src/main/java/domain/security/service/RefreshTokenService.java
  backend/text-me/src/main/java/domain/user/controller/UserController.java
  backend/text-me/src/main/java/domain/user/dto/request/TokenRefreshRequest.java
  backend/text-me/src/main/java/domain/user/dto/response/TokenRefreshResponse.java
  frontend/.gitignore
Labels: 우선순위 ⭐, 백 🐻, 개발 🧑‍💻

#38 메인 페이지 디자인 수정 (#37)
  frontend/.babelrc
  frontend/components/main/RoomEnterForm.tsx
  frontend/package.json
  frontend/pages/_document.tsx
  frontend/pages/index.tsx
  frontend/yarn.lock
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#28 편지 작성 컴포넌트 구현
  frontend/.babelrc
  frontend/.yarn/cache/@babel-generator-npm-7.20.5-d08ff0a892-31c10d1e12 2.zip
  frontend/.yarn/cache/@babel-parser-npm-7.20.5-2b25154357-e8d514ce0a 2.zip
  frontend/.yarn/cache/@babel-traverse-npm-7.20.5-dc0e9498d7-c7fed46861 2.zip
  frontend/.yarn/cache/@babel-types-npm-7.20.5-3ee242b980-773f0a1ad9 2.zip
  frontend/.yarn/cache/@emotion-is-prop-valid-npm-1.2.0-332d343e3d-cc7a19850a 2.zip
  frontend/.yarn/cache/@emotion-memoize-npm-0.8.0-c5dd451828-c87bb110b8 2.zip
  frontend/.yarn/cache/@emotion-stylis-npm-0.8.5-3e9db8959f-67ff595844 2.zip
  frontend/.yarn/cache/@emotion-unitless-npm-0.7.5-14e1171640-f976e5345b 2.zip
  frontend/.yarn/cache/@popperjs-core-npm-2.11.6-5bcdc104bd-47fb328cec 2.zip
  frontend/.yarn/cache/@types-hoist-non-react-statics-npm-3.3.1-c0081332b2-2c0778570d 2.zip
  frontend/.yarn/cache/@types-react-datepicker-npm-4.8.0-436ed0cec3-4404d6bd27 2.zip
  frontend/.yarn/cache/@types-styled-components-npm-5.1.26-aabda06611-84f53b3101 2.zip
  frontend/.yarn/cache/babel-plugin-styled-components-npm-2.0.7-543710bd48-80b06b10db 2.zip
  frontend/.yarn/cache/babel-plugin-syntax-jsx-npm-6.18.0-fcf0a98a71-0c7ce5b81d 2.zip
  frontend/.yarn/cache/camelize-npm-1.0.1-d86ebe085a-91d8611d09 2.zip
  frontend/.yarn/cache/classnames-npm-2.3.2-d2fdae468d-2c62199789 2.zip
  frontend/.yarn/cache/css-color-keywords-npm-1.0.0-fc176df58b-8f125e3ad4 2.zip
  frontend/.yarn/cache/css-to-react-native-npm-3.0.0-ab07d67d74-98a2e9d4fb 2.zip
  frontend/.yarn/cache/date-fns-npm-2.29.3-fef7e3c72c-e01cf5b62a 2.zip
  frontend/.yarn/cache/hoist-non-react-statics-npm-3.3.2-e7b709e6c1-b153827042 2.zip
  frontend/.yarn/cache/html-to-image-npm-1.10.9-668c589562-e46163d0da 2.zip
  frontend/.yarn/cache/postcss-value-parser-npm-4.2.0-3cef602a6a-819ffab0c9 2.zip
  frontend/.yarn/cache/react-card-flip-npm-1.2.0-0a7f83b87f-b317477909 2.zip
  frontend/.yarn/cache/react-datepicker-npm-4.8.0-40274fac86-d31a1002c5 2.zip
  frontend/.yarn/cache/react-fast-compare-npm-3.2.0-fbfa6627d9-8ef272c825 2.zip
  frontend/.yarn/cache/react-onclickoutside-npm-6.12.2-61c80f0d9a-a0c7f4fbcf 2.zip
  frontend/.yarn/cache/react-popper-npm-2.3.0-1045578379-837111c987 2.zip
  frontend/.yarn/cache/shallowequal-npm-1.1.0-6688d419cb-f4c1de0837 2.zip
  frontend/.yarn/cache/styled-components-npm-5.3.6-934fe4f344-68eac1e451 2.zip
  frontend/.yarn/cache/warning-npm-4.0.3-291e921d6d-4f2cb6a957 2.zip
  frontend/components/layout/Layout 2.tsx
  frontend/components/write/PictureDatePicker.tsx
  frontend/components/write/snowman.png
  frontend/package.json
  frontend/pages/[uid]/write/preview-card-picture.tsx
  frontend/pages/[uid]/write/select-card-picture.tsx
  frontend/pages/[uid]/write/send-complete.tsx
  frontend/pages/[uid]/write/write-letter.tsx
  frontend/pages/preview-card-picture/index.tsx
  frontend/pages/select-card-picture/index.tsx
  frontend/public/static/images/icon-camera.png
  frontend/public/static/images/room-background 2.png
  frontend/public/static/images/select-picture.png
  frontend/stores/useLetterInfo.ts
  frontend/styles/cardBackground.css
  frontend/styles/dataPicker.css
  frontend/styles/theme/Theme 2.ts
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#41 로그인과 회원가입 페이지 (#40)
  frontend/components/common/icons/ArrowBackIcon.tsx
  frontend/components/main/RoomEnterForm.tsx
  frontend/components/room/Letter.tsx
  frontend/components/room/LettersContainer.tsx
  frontend/components/room/icons/PlusIcon.tsx
  frontend/components/room/icons/SaveIcon.tsx
  frontend/components/room/icons/ShareIcon.tsx
  frontend/mocks/handlers/members.js
  frontend/pages/index.tsx
  frontend/pages/signin.tsx
  frontend/pages/signup.tsx
  frontend/styles/components/Button.ts
  frontend/styles/components/Form.ts
  frontend/styles/components/Title.ts
  node_modules/.yarn-integrity
  yarn.lock
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#49 Letter 관련 API 생성 (#48)
  backend/text-me/src/main/java/domain/letter/controller/LetterController.java
  backend/text-me/src/main/java/domain/letter/dto/request/LetterRequest.java
  backend/text-me/src/main/java/domain/letter/dto/response/LetterResponse.java
  backend/text-me/src/main/java/domain/letter/entity/Letter.java
  backend/text-me/src/main/java/domain/letter/exception/LetterNotFoundException.java
  backend/text-me/src/main/java/domain/letter/repository/LetterRepository.java
  backend/text-me/src/main/java/domain/letter/service/LetterService.java
  backend/text-me/src/main/java/domain/security/jwt/JwtAuth.java
  backend/text-me/src/main/java/error/ErrorCode.java
  backend/text-me/src/main/resources/application.yml
Labels: 백 🐻, 개발 🧑‍💻

#44 카드 선택 페이지 mock 연동(#42)
  frontend/mocks/data/cards.js
  frontend/mocks/handlers/cards.js
  frontend/mocks/servers.js
  frontend/mocks/workers.js
  frontend/pages/[uid]/write/select-card-picture.tsx
  frontend/pages/index.tsx
  frontend/stores/useCardPicture.ts
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#52 cicd 스크립트 백과 프론트 분리 (#32)
  .idea/misc.xml
  backend/text-me/.github/workflows/build-backend.yml
  backend/text-me/.github/workflows/build-frontend.yml
  backend/text-me/.github/workflows/deploy-backend.yml
  backend/text-me/.github/workflows/deploy-frontend.yml
  node_modules/.idea/misc.xml
  node_modules/.idea/modules.xml
  node_modules/.idea/node_modules.iml
  node_modules/.idea/vcs.xml
  node_modules/.idea/workspace.xml
Labels: 우선순위 ⭐, 백 🐻, 개발 🧑‍💻

#53 worksflow 디렉토리 위치 변경 (#32)
  .github/workflows/build-backend.yml
  .github/workflows/build-frontend.yml
  .github/workflows/deploy-backend.yml
  .github/workflows/deploy-frontend.yml
Labels: 백 🐻, 개발 🧑‍💻

#58 LetterResponse 필드 어노테이션 변경(#57)
  backend/text-me/src/main/java/gifterz/textme/domain/letter/dto/request/LetterRequest.java
Labels: 우선순위 ⭐, 개발 🧑‍💻, 리팩터링 🔧

#61 feature: 편지 작성 완료 컴포넌트 구현(#51)
  frontend/pages/[uid]/write/preview-card-picture.tsx
  frontend/pages/[uid]/write/send-complete.tsx
  frontend/pages/signin.tsx
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#60 Swagger 적용(#59)
  backend/text-me/build.gradle
  backend/text-me/src/main/java/gifterz/textme/config/OpenApiConfig.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/controller/LetterController.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/entity/Letter.java
  backend/text-me/src/main/java/gifterz/textme/domain/security/WebSecurityConfig.java
  backend/text-me/src/main/java/gifterz/textme/domain/security/jwt/AuthTokenFilter.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/controller/UserController.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/service/UserService.java
  backend/text-me/src/main/resources/application.yml
Labels: 우선순위 ⭐, 개발 🧑‍💻

#64 편지 쓰기 페이지 오류 해결 (#63)
  frontend/components/write/PictureDatePicker.tsx
  frontend/components/write/icons/CameraIcon.tsx
  frontend/components/write/snowman.png
  frontend/mocks/handlers/room.js
  frontend/pages/[uid]/index.tsx
  frontend/pages/[uid]/write/preview-card-picture.tsx
  frontend/pages/[uid]/write/select-card-picture.tsx
  frontend/pages/[uid]/write/send-complete.tsx
  frontend/pages/[uid]/write/write-letter.tsx
  frontend/stores/useLetterInfo.ts
  frontend/stores/useRoomInfo.ts
  frontend/stores/useSendLetter.ts
Labels: 버그 🕷, 프론트 🐻‍❄️

#66 jwt 인증 인가 구현(#62)
  frontend/.yarn/cache/@types-cookie-npm-0.3.3-a5ddc16db3-450c930d79.zip
  frontend/.yarn/cache/universal-cookie-npm-4.0.4-aa9b4bcfbf-bb2bafa7eb.zip
  frontend/auth/api.ts
  frontend/auth/refresh.ts
  frontend/components/common/Cookie.ts
  frontend/package.json
  frontend/pages/signin.tsx
  frontend/yarn.lock
Labels: 우선순위 ⭐⭐⭐, 프론트 🐻‍❄️, 개발 🧑‍💻

#71 빌드 스크립트 수정 (#65)
  .github/workflows/build-backend.yml
  .github/workflows/build-frontend.yml
Labels: 버그 🕷, 우선순위 ⭐⭐⭐, 백 🐻, 개발 🧑‍💻

#72 백엔드 빌드 스크립트 수정 (#65)
  .github/workflows/build-backend.yml
Labels: 버그 🕷, 백 🐻, 개발 🧑‍💻

#74 빌드 에러 해결 (#73)
  frontend/pages/[uid]/write/send-complete.tsx
Labels: 버그 🕷, 프론트 🐻‍❄️

#75 빌드 스크립트 수정 (#65)
  .github/workflows/build-backend.yml
  .github/workflows/build-frontend.yml
Labels: 백 🐻, 개발 🧑‍💻

#76 업로드 파일 S3에 저장 (#69)
  backend/text-me/build.gradle
  backend/text-me/src/main/java/gifterz/textme/config/AwsConfig.java
  backend/text-me/src/main/java/gifterz/textme/config/OpenApiConfig.java
  backend/text-me/src/main/java/gifterz/textme/domain/security/WebSecurityConfig.java
  backend/text-me/src/main/java/gifterz/textme/error/ErrorCode.java
  backend/text-me/src/main/java/gifterz/textme/s3Proxy/FileUploadController.java
  backend/text-me/src/main/java/gifterz/textme/s3Proxy/S3Service.java
  backend/text-me/src/main/java/gifterz/textme/s3Proxy/exception/InvalidFileContentException.java
  backend/text-me/src/main/resources/application.yml
Labels: 우선순위 ⭐⭐, 백 🐻, 개발 🧑‍💻

#77 백엔드 빌드 스크립트 수정 (#65)
  .github/workflows/build-backend.yml
Labels: 버그 🕷, 백 🐻, 개발 🧑‍💻

#80 백엔드 빌드 스크립트 수정 (#65)
  .github/workflows/build-backend.yml
Labels: 버그 🕷, 백 🐻, 개발 🧑‍💻

#86 백엔드 빌드 스크립트 수정 (#65)
  .github/workflows/build-backend.yml
Labels: 버그 🕷, 백 🐻, 개발 🧑‍💻

#84 사용자 정보 조회(#83)
  backend/text-me/src/main/java/gifterz/textme/domain/user/controller/UserController.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/service/UserService.java
Labels: 우선순위 ⭐, 백 🐻, 개발 🧑‍💻

#90 백엔드 빌드 스크립트 수정 (#65)
  .github/workflows/build-backend.yml
  .github/workflows/deploy-backend.yml
Labels: 버그 🕷, 백 🐻, 개발 🧑‍💻

#91 사용자 이름 수정 (#88, #92)
  backend/text-me/src/main/java/gifterz/textme/domain/user/controller/UserController.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/entity/User.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/service/UserService.java
Labels: 우선순위 ⭐, 백 🐻, 개발 🧑‍💻

#95 feat: 카드 업로드 (#94)
  backend/text-me/src/main/java/gifterz/textme/config/OpenApiConfig.java
  backend/text-me/src/main/java/gifterz/textme/domain/card/controller/CardController.java
  backend/text-me/src/main/java/gifterz/textme/domain/card/entity/Card.java
  backend/text-me/src/main/java/gifterz/textme/domain/card/repository/CardRepository.java
  backend/text-me/src/main/java/gifterz/textme/domain/card/service/CardService.java
  backend/text-me/src/main/java/gifterz/textme/domain/security/WebSecurityConfig.java
Labels: 우선순위 ⭐⭐, 백 🐻, 개발 🧑‍💻

#96 이미지 빌드 권한 부여를 위한 인증 추가 (#65)
  .github/workflows/build-backend.yml
Labels: 버그 🕷, 백 🐻, 개발 🧑‍💻

#98 카드 전체 조회 (#97)
  backend/text-me/src/main/java/gifterz/textme/domain/card/controller/CardController.java
  backend/text-me/src/main/java/gifterz/textme/domain/card/service/CardService.java
  backend/text-me/src/main/java/gifterz/textme/s3Proxy/S3Service.java
Labels: 우선순위 ⭐⭐, 백 🐻, 개발 🧑‍💻

#99 jib 빌드 위한 권한 문제 해결 (#65)
  backend/text-me/Dockerfile
  backend/text-me/build.gradle
Labels: 버그 🕷, 백 🐻, 개발 🧑‍💻

#100 jib 빌드 위한 권한 문제 해결 (#65)
  .github/workflows/build-backend.yml
  backend/text-me/build.gradle
Labels: 버그 🕷, 백 🐻, 개발 🧑‍💻

#102 도커 이미지 tag 수정 (#65)
  .github/workflows/build-backend.yml
  backend/text-me/build.gradle
Labels: 버그 🕷, 백 🐻, 개발 🧑‍💻

#103 도커 이미지 tag 수정 (#65)
  .github/workflows/build-backend.yml
Labels: 버그 🕷, 백 🐻, 개발 🧑‍💻

#105 방 화면 수정 (#67)
  frontend/components/layout/Layout 2.tsx
  frontend/components/layout/Layout.tsx
  frontend/components/room/ButtonsContainer.tsx
  frontend/components/room/LettersContainer.tsx
  frontend/components/room/SaveContainer.tsx
  frontend/components/room/SaveModal.tsx
  frontend/components/room/icons/CameraIcon.tsx
  frontend/components/room/icons/PlusIcon.tsx
  frontend/components/room/icons/SaveIcon.tsx
  frontend/pages/[uid]/index.tsx
  frontend/public/static/images/icon-camera.png
  frontend/public/static/images/room-background 2.png
  frontend/public/static/images/room-background.png
  frontend/stores/useCaptureMode.ts
  frontend/styles/components/Button.ts
  frontend/styles/globals.css
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#109 UserResponse객체 리팩토링 (#108)
  backend/text-me/src/main/java/gifterz/textme/domain/user/dto/response/UserResponse.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/service/UserService.java
Labels: 백 🐻, 리팩터링 🔧

#111 이메일을 사용해 사용자 정보 조회 (#110)
  backend/text-me/src/main/java/gifterz/textme/domain/user/controller/UserController.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/service/UserService.java
Labels: 우선순위 ⭐, 백 🐻, 개발 🧑‍💻

#113 feat: 사용자 id를 사용해 사용자 정보 조회 (#112)
  backend/text-me/src/main/java/gifterz/textme/domain/user/controller/UserController.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/service/UserService.java
Labels: 우선순위 ⭐, 백 🐻, 개발 🧑‍💻

#115 카드 url 전체 조회 (#114)
  backend/text-me/src/main/java/gifterz/textme/domain/card/service/CardService.java
Labels: 우선순위 ⭐⭐, 백 🐻, 리팩터링 🔧

#118 feat: 상태데이터를 추가 (#117)
  backend/text-me/src/main/java/gifterz/textme/domain/card/entity/Card.java
  backend/text-me/src/main/java/gifterz/textme/domain/entity/BaseEntity.java
  backend/text-me/src/main/java/gifterz/textme/domain/entity/StatusType.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/entity/Letter.java
  backend/text-me/src/main/java/gifterz/textme/domain/security/entity/RefreshToken.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/entity/User.java
Labels: 우선순위 ⭐, 백 🐻, 개발 🧑‍💻

#116 API 수정(#106)
  frontend/auth/visitorApi.ts
  frontend/components/mypage/NicknameContainer.tsx
  frontend/components/room/Letter.tsx
  frontend/components/room/LetterView.tsx
  frontend/pages/[uid]/index.tsx
  frontend/pages/[uid]/write/select-card-picture.tsx
  frontend/pages/[uid]/write/send-complete.tsx
  frontend/pages/[uid]/write/write-letter.tsx
  frontend/pages/signin.tsx
  frontend/pages/signup.tsx
  frontend/stores/useCardPicture.ts
  frontend/stores/useLetterView.ts
  frontend/stores/useLetters.ts
  frontend/stores/useMembers.ts
  frontend/stores/useRoomEnter.ts
  frontend/stores/useRoomInfo.ts
  frontend/stores/useSendLetter.ts
  frontend/types/index.ts
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#121 CORS해결 (#120)
  backend/text-me/src/main/java/gifterz/textme/domain/security/WebConfig.java
Labels: 우선순위 ⭐⭐, 백 🐻, 개발 🧑‍💻

#122 도커 이미지 tag 수정 (#65)
  .github/workflows/build-backend.yml
Labels: 버그 🕷, 백 🐻, 개발 🧑‍💻

#124 도커 이미지 tag 수정 (#65)
  .github/workflows/build-backend.yml
Labels: 버그 🕷, 백 🐻, 개발 🧑‍💻

#125 도커 이미지 tag 수정 (#65)
  .github/workflows/build-backend.yml
Labels: 버그 🕷, 백 🐻, 개발 🧑‍💻

#126 도커 파일 삭제 (#65)
  backend/text-me/Dockerfile
Labels: 백 🐻, 개발 🧑‍💻, 리팩터링 🔧

#127 도커 테깅 스크립트 삭제 (#65)
  .github/workflows/build-backend.yml
Labels: 백 🐻, 개발 🧑‍💻, 리팩터링 🔧

#128 도커 테깅 스크립트 수정 (#65)
  .github/workflows/build-backend.yml
Labels: 백 🐻, 개발 🧑‍💻, 리팩터링 🔧

#129 도커 테깅 스크립트 수정 (#65)
  .github/workflows/build-backend.yml
Labels: 백 🐻, 개발 🧑‍💻, 리팩터링 🔧

#130 도커 테깅 스크립트 수정 (#65)
  .github/workflows/build-backend.yml
Labels: 백 🐻, 개발 🧑‍💻, 리팩터링 🔧

#131 도커 테깅 스크립트 수정 (#65)
  .github/workflows/build-backend.yml
Labels: 백 🐻, 개발 🧑‍💻, 리팩터링 🔧

#133 백엔드 배포 스크립트 수정 (#132)
  .github/workflows/deploy-backend.yml
Labels: 백 🐻, 개발 🧑‍💻, 리팩터링 🔧

#134 백엔드 빌드 스크립트 환경변수 추가 (#132)
  .github/workflows/build-backend.yml
  .github/workflows/deploy-backend.yml
Labels: 백 🐻, 개발 🧑‍💻

#136 fix: CORS해결 (#135)
  backend/text-me/src/main/java/gifterz/textme/domain/security/WebConfig.java
Labels: 버그 🕷, 우선순위 ⭐⭐, 백 🐻

#137 방 디자인 svg로 수정 (#107)
  frontend/components/room/Background.tsx
  frontend/components/room/ButtonsContainer.tsx
  frontend/components/room/Letter.tsx
  frontend/components/room/LettersContainer.tsx
  frontend/components/room/LettersMove.tsx
  frontend/components/room/SaveModal.tsx
  frontend/components/room/icons/HomeIcon.tsx
  frontend/mocks/data/letters.js
  frontend/pages/[uid]/index.tsx
  frontend/public/static/images/room-background.png
  frontend/public/static/images/room-default.png
  frontend/public/static/images/room-line-1.png
  frontend/public/static/images/room-line-2.png
  frontend/styles/components/Modal.ts
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#142 백엔드 빌드 배포 스크립트 수정 (#132)
  .github/workflows/build-backend.yml
  .github/workflows/deploy-backend.yml
Labels: 백 🐻, 개발 🧑‍💻, 리팩터링 🔧

#144 백엔드 빌드 스크립트 환경변수 추가 (#132)
  .github/workflows/deploy-backend.yml
Labels: 백 🐻, 개발 🧑‍💻, 리팩터링 🔧

#139 배경 반응형 계산 (#107)
  frontend/components/room/Background.tsx
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#147 API 수정(#138)
  frontend/auth/refresh.ts
  frontend/components/main/RoomEnterForm.tsx
  frontend/components/room/Background.tsx
  frontend/components/room/Letter.tsx
  frontend/components/room/LetterView.tsx
  frontend/components/room/LetterViewContainer.tsx
  frontend/components/room/LettersContainer.tsx
  frontend/components/room/icons/MoveNextIcon.tsx
  frontend/components/room/icons/MovePrevIcon.tsx
  frontend/pages/[uid]/index.tsx
  frontend/pages/[uid]/write/select-card-picture.tsx
  frontend/pages/index.tsx
  frontend/pages/signin.tsx
  frontend/stores/useCardPicture.ts
  frontend/stores/useLetterView.ts
  frontend/stores/useLetters.ts
  frontend/stores/useMembers.ts
  frontend/stores/useRoomEnter.ts
  frontend/stores/useRoomInfo.ts
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#150 Authentication response 리팩토링 (#149)
  backend/text-me/src/main/java/gifterz/textme/domain/security/service/RefreshTokenService.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/dto/response/LoginResponse.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/dto/response/TokenRefreshResponse.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/service/UserService.java
Labels: 우선순위 ⭐⭐, 백 🐻, 리팩터링 🔧

#152 전반적인 디자인 수정 (#145)
  .github/workflows/deploy-frontend.yml
  frontend/components/common/ErrorContainer.tsx
  frontend/components/common/Logo.tsx
  frontend/components/mypage/NicknameContainer.tsx
  frontend/components/room/Background.tsx
  frontend/components/room/LetterView.tsx
  frontend/components/room/LettersContainer.tsx
  frontend/components/room/SaveModal.tsx
  frontend/components/room/ShareModal.tsx
  frontend/pages/[uid]/write/preview-card-picture.tsx
  frontend/pages/[uid]/write/select-card-picture.tsx
  frontend/pages/[uid]/write/send-complete.tsx
  frontend/pages/[uid]/write/write-letter.tsx
  frontend/pages/index.tsx
  frontend/pages/mypage.tsx
  frontend/pages/signin.tsx
  frontend/pages/signup.tsx
  frontend/public/static/fonts/GangwonEduSaeeumMedium.woff
  frontend/public/static/fonts/GangwonEduSaeeumMedium.woff2
  frontend/public/static/fonts/style.css
  frontend/styles/components/Layout.ts
  node_modules/.idea/misc.xml
  node_modules/.idea/modules.xml
  node_modules/.idea/node_modules.iml
  node_modules/.idea/vcs.xml
  node_modules/.idea/workspace.xml
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#151 토큰 재요청 로직 수정(#148)
  frontend/auth/refresh.ts
  frontend/pages/signin.tsx
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#159 배포 스크립트 수정 (#132)
  .github/workflows/deploy-backend.yml
  backend/text-me/.gitignore
  backend/text-me/src/main/resources/application.yml
Labels: 백 🐻, 개발 🧑‍💻, 리팩터링 🔧

#162 cloud.aws.stack 적용안되는 현상 해결(#160)
  backend/text-me/build.gradle
  backend/text-me/src/main/resources/application.yml
Labels: 버그 🕷, 우선순위 ⭐⭐, 백 🐻

#155 예외 상황 핸들링 (#153)
  frontend/components/main/RoomEnterForm.tsx
  frontend/components/room/ButtonsContainer.tsx
  frontend/components/room/Letter.tsx
  frontend/components/room/ShareModal.tsx
  frontend/pages/[uid]/index.tsx
  frontend/pages/[uid]/write/select-card-picture.tsx
  frontend/pages/index.tsx
  frontend/pages/mypage.tsx
  frontend/pages/signin.tsx
  frontend/stores/useCardPicture.ts
  frontend/stores/useMembers.ts
  frontend/stores/useRoomEnter.ts
  frontend/styles/components/Button.ts
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#165 feat: 배포 스크립트 위치 수정 (#163)
  frontend/.yarn/cache/cross-env-npm-7.0.3-96d81820f4-26f2f3ea2a.zip
  frontend/package.json
  frontend/yarn.lock
  node_modules/.bin/cross-env
  node_modules/.bin/cross-env-shell
  node_modules/.bin/node-which
  node_modules/.yarn-integrity
  node_modules/cross-env/CHANGELOG.md
  node_modules/cross-env/LICENSE
  node_modules/cross-env/README.md
  node_modules/cross-env/package.json
  node_modules/cross-env/src/bin/cross-env-shell.js
  node_modules/cross-env/src/bin/cross-env.js
  node_modules/cross-env/src/command.js
  node_modules/cross-env/src/index.js
  node_modules/cross-env/src/is-windows.js
  node_modules/cross-env/src/variable.js
  node_modules/cross-spawn/CHANGELOG.md
  node_modules/cross-spawn/LICENSE
  node_modules/cross-spawn/README.md
  node_modules/cross-spawn/index.js
  node_modules/cross-spawn/lib/enoent.js
  node_modules/cross-spawn/lib/parse.js
  node_modules/cross-spawn/lib/util/escape.js
  node_modules/cross-spawn/lib/util/readShebang.js
  node_modules/cross-spawn/lib/util/resolveCommand.js
  node_modules/cross-spawn/node_modules/.bin/node-which
  node_modules/cross-spawn/package.json
  node_modules/isexe/.npmignore
  node_modules/isexe/LICENSE
  node_modules/isexe/README.md
  node_modules/isexe/index.js
  node_modules/isexe/mode.js
  node_modules/isexe/package.json
  node_modules/isexe/test/basic.js
  node_modules/isexe/windows.js
  node_modules/path-key/index.d.ts
  node_modules/path-key/index.js
  node_modules/path-key/license
  node_modules/path-key/package.json
  node_modules/path-key/readme.md
  node_modules/shebang-command/index.js
  node_modules/shebang-command/license
  node_modules/shebang-command/package.json
  node_modules/shebang-command/readme.md
  node_modules/shebang-regex/index.d.ts
  node_modules/shebang-regex/index.js
  node_modules/shebang-regex/license
  node_modules/shebang-regex/package.json
  node_modules/shebang-regex/readme.md
  node_modules/which/CHANGELOG.md
  node_modules/which/LICENSE
  node_modules/which/README.md
  node_modules/which/bin/node-which
  node_modules/which/package.json
  node_modules/which/which.js
  package.json
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#156 구글 애널리틱스 추적 추가(#154)
  frontend/.yarn/cache/@types-gtag.js-npm-0.0.12-6390d727c7-34efc27fbf.zip
  frontend/lib/gtag.ts
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/pages/_document.tsx
  frontend/yarn.lock
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#158 Alert Modal 구현(#157)
  frontend/components/room/AlertModal.tsx
  frontend/components/room/Background.tsx
  frontend/components/room/SaveModal.tsx
  frontend/pages/[uid]/index.tsx
  frontend/stores/useAlertModal.ts
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#170 오류처리와 자잘한 오류 해결(#167)
  frontend/components/room/LetterView.tsx
  frontend/components/room/SaveModal.tsx
  frontend/next.config.js
  frontend/pages/_app.tsx
  frontend/pages/_document.tsx
  frontend/pages/signin.tsx
  frontend/pages/signup.tsx
  frontend/public/favicon.ico
  frontend/stores/useRoomEnter.ts
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#171 사용자 존재하지 않을 때의 에러메시지 수정(#169)
  backend/text-me/src/main/java/gifterz/textme/error/ErrorCode.java
Labels: 우선순위 ⭐, 백 🐻, 리팩터링 🔧

#173 head title 추가(#172)
  frontend/auth/refresh.ts
  frontend/pages/[uid]/index.tsx
  frontend/pages/[uid]/write/preview-card-picture.tsx
  frontend/pages/[uid]/write/select-card-picture.tsx
  frontend/pages/[uid]/write/send-complete.tsx
  frontend/pages/[uid]/write/write-letter.tsx
  frontend/pages/_app.tsx
  frontend/pages/index.tsx
  frontend/pages/mypage.tsx
  frontend/pages/signin.tsx
  frontend/pages/signup.tsx
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#176 디자인 이슈 해결 (#175)
  frontend/components/common/ErrorContainer.tsx
  frontend/components/layout/Layout.tsx
  frontend/components/room/Background.tsx
  frontend/components/room/icons/CameraIcon.tsx
  frontend/components/room/icons/HomeIcon.tsx
  frontend/components/room/icons/MenuIcon.tsx
  frontend/components/room/icons/ShareIcon.tsx
  frontend/pages/_app.tsx
  frontend/pages/index.tsx
  frontend/styles/components/Frame.ts
  frontend/styles/components/Modal.ts
  frontend/styles/globals.css
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#181 카드 업로드 API 설정(#178)
  frontend/components/room/LettersContainer.tsx
  frontend/pages/[uid]/write/select-card-picture.tsx
  frontend/stores/useCardPicture.ts
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#179 타이틀과 메타태그 추가 (#177)
  frontend/pages/[uid]/index.tsx
  frontend/pages/[uid]/write/preview-card-picture.tsx
  frontend/pages/[uid]/write/select-card-picture.tsx
  frontend/pages/[uid]/write/send-complete.tsx
  frontend/pages/[uid]/write/write-letter.tsx
  frontend/pages/api/hello.ts
  frontend/pages/mypage.tsx
  frontend/pages/signin.tsx
  frontend/pages/signup.tsx
  frontend/public/static/images/meta-card.png
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#182 편지 전체 조회 API 리팩토링(#180)
  backend/text-me/src/main/java/gifterz/textme/domain/letter/repository/LetterRepository.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/service/LetterService.java
Labels: 우선순위 ⭐⭐, 백 🐻, 리팩터링 🔧

#185 프리뷰 이미지 포지션 변경(#184)
  frontend/pages/[uid]/write/preview-card-picture.tsx
  frontend/pages/[uid]/write/write-letter.tsx
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#187 파일 업로드 크기 리사이징(#186)
  backend/text-me/build.gradle
  backend/text-me/src/main/java/gifterz/textme/s3Proxy/S3Service.java
  backend/text-me/src/main/resources/application.yml
Labels: 우선순위 ⭐⭐, 백 🐻, 개발 🧑‍💻

#191 업로드 최대 크기 초과 시 validation처리(#190)
  backend/text-me/src/main/java/gifterz/textme/s3Proxy/S3Service.java
Labels: 우선순위 ⭐⭐, 백 🐻, 개발 🧑‍💻

#189 발생할 수 있는 예외 처리 (#188)
  frontend/components/common/LoadingContainer.tsx
  frontend/components/main/RoomEnterForm.tsx
  frontend/components/mypage/NicknameContainer.tsx
  frontend/components/room/Background.tsx
  frontend/components/room/LetterView.tsx
  frontend/components/room/LettersContainer.tsx
  frontend/pages/[uid]/index.tsx
  frontend/pages/[uid]/write/preview-card-picture.tsx
  frontend/pages/[uid]/write/select-card-picture.tsx
  frontend/pages/[uid]/write/send-complete.tsx
  frontend/pages/[uid]/write/write-letter.tsx
  frontend/pages/_app.tsx
  frontend/pages/_document.tsx
  frontend/pages/mypage.tsx
  frontend/public/static/fonts/UhBee-MiMi-Bold.woff
  frontend/public/static/fonts/UhBee-MiMi.woff
  frontend/public/static/fonts/style.css
  frontend/stores/useCardPicture.ts
  frontend/stores/useRoomInfo.ts
  frontend/styles/indicators/Loader.ts
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#192 사용자아이디 암호화(#174)
  backend/text-me/src/main/java/gifterz/textme/domain/letter/controller/LetterController.java
  backend/text-me/src/main/java/gifterz/textme/domain/security/service/AesUtils.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/controller/UserController.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/dto/response/LoginResponse.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/dto/response/UserResponse.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/service/UserService.java
Labels: 우선순위 ⭐⭐⭐, 백 🐻, 개발 🧑‍💻

#194 사용자아이디 암호화(#174)
  backend/text-me/src/main/java/gifterz/textme/domain/letter/dto/request/LetterRequest.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/service/LetterService.java
  backend/text-me/src/main/java/gifterz/textme/domain/security/service/AesUtils.java
Labels: 우선순위 ⭐⭐, 백 🐻, 개발 🧑‍💻

#198 토큰 갱신 요청 객체 리팩토링(#197)
  backend/text-me/src/main/java/gifterz/textme/domain/user/controller/UserController.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/dto/request/TokenRefreshRequest.java
Labels: 우선순위 ⭐⭐, 백 🐻, 리팩터링 🔧

#199 API 관련 수정 (#196)
  frontend/auth/Cookie.ts
  frontend/auth/refresh.ts
  frontend/components/common/Cookie.ts
  frontend/components/main/RoomEnterForm.tsx
  frontend/components/room/Background.tsx
  frontend/components/room/Letter.tsx
  frontend/components/room/LettersContainer.tsx
  frontend/pages/[uid]/index.tsx
  frontend/pages/[uid]/write/send-complete.tsx
  frontend/pages/[uid]/write/write-letter.tsx
  frontend/pages/signin.tsx
  frontend/stores/useLetters.ts
  frontend/stores/useMembers.ts
  frontend/stores/useRoomEnter.ts
  frontend/stores/useRoomInfo.ts
  frontend/stores/useSendLetter.ts
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#202 파일 업로드 수정(#201)
  frontend/pages/[uid]/write/preview-card-picture.tsx
  frontend/pages/[uid]/write/select-card-picture.tsx
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#205 이미지 업로드 오류 수정 (#201)
  frontend/.yarn/cache/blueimp-canvas-to-blob-npm-3.29.0-9f03921b3a-6a55b90fbe.zip
  frontend/.yarn/cache/compressorjs-npm-1.1.1-5b682437ea-b4899567df.zip
  frontend/.yarn/cache/is-blob-npm-2.1.0-9aa6e9b797-ce24917bf5.zip
  frontend/components/mypage/NicknameContainer.tsx
  frontend/package.json
  frontend/pages/[uid]/write/select-card-picture.tsx
  frontend/pages/signin.tsx
  frontend/pages/signup.tsx
  frontend/stores/useCardPicture.ts
  frontend/stores/useRoomEnter.ts
  frontend/yarn.lock
Labels: 버그 🕷, 개발 🧑‍💻

#207 알림 기능 일부 구현 (#168)
  backend/text-me/src/main/java/gifterz/textme/domain/letter/service/LetterService.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/AsyncConfig.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/EmitterRepository.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/EmitterRepositoryImpl.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/Notification.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/NotificationContent.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/NotificationController.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/NotificationListener.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/NotificationRepository.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/NotificationRequestDto.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/NotificationResponseDto.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/NotificationService.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/RelatedURL.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/service/UserService.java
  backend/text-me/src/test/java/gifterz/textme/domain/notification/EmitterRepositoryImplTest.java
  backend/text-me/src/test/java/gifterz/textme/domain/notification/NotificationContentTest.java
  backend/text-me/src/test/java/gifterz/textme/domain/notification/RelatedURLTest.java
Labels: 백 🐻, 개발 🧑‍💻

#210 전체 편지 조회 응답 리팩토링(#209)
  backend/text-me/src/main/java/gifterz/textme/domain/letter/controller/LetterController.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/dto/response/AllLetterResponse.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/service/LetterService.java
Labels: 우선순위 ⭐⭐, 백 🐻, 리팩터링 🔧

#213 리사이징 목표 너비 감소(#212)
  backend/text-me/src/main/java/gifterz/textme/s3Proxy/S3Service.java
Labels: 버그 🕷, 우선순위 ⭐⭐, 백 🐻

#214 편지 전송시 이벤트 발생 로직 추가 (#168)
  backend/text-me/src/main/java/gifterz/textme/domain/letter/entity/Letter.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/service/LetterService.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/AsyncConfig.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/NotificationListener.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/NotificationRequest.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/NotificationResponse.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/NotificationResponseDto.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/NotificationService.java
Labels: 백 🐻, 개발 🧑‍💻

#215 [v1.0.4] text-me 배포
  README.md
  backend/text-me/src/main/java/gifterz/textme/domain/letter/controller/LetterController.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/dto/response/AllLetterResponse.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/entity/Letter.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/service/LetterService.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/AsyncConfig.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/EmitterRepository.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/EmitterRepositoryImpl.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/Notification.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/NotificationContent.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/NotificationController.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/NotificationListener.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/NotificationRepository.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/NotificationRequest.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/NotificationResponse.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/NotificationService.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/RelatedURL.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/service/UserService.java
  backend/text-me/src/main/java/gifterz/textme/s3Proxy/S3Service.java
  backend/text-me/src/test/java/gifterz/textme/domain/notification/EmitterRepositoryImplTest.java
  backend/text-me/src/test/java/gifterz/textme/domain/notification/NotificationContentTest.java
  backend/text-me/src/test/java/gifterz/textme/domain/notification/RelatedURLTest.java
Labels: 프론트 🐻‍❄️, 백 🐻

#217 ImageIO가 스트림을 읽을수 없을시 예외처리 (#216)
  backend/text-me/src/main/java/gifterz/textme/error/ErrorCode.java
  backend/text-me/src/main/java/gifterz/textme/s3Proxy/S3Service.java
  backend/text-me/src/main/java/gifterz/textme/s3Proxy/exception/InvalidFileImage.java
  backend/text-me/src/main/java/gifterz/textme/s3Proxy/exception/failFileResize.java
Labels: 버그 🕷, 백 🐻, 개발 🧑‍💻

#219 편지조회 취약점 해결(#218)
  backend/text-me/src/main/java/gifterz/textme/domain/letter/service/LetterService.java
Labels: 버그 🕷, 우선순위 ⭐⭐⭐, 백 🐻

#226 비밀번호 패턴 변경(#223)
  frontend/components/room/LetterView.tsx
  frontend/pages/signin.tsx
  frontend/pages/signup.tsx
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#224 비밀번호 정책 변경(#221)
  backend/text-me/src/main/java/gifterz/textme/domain/user/dto/request/LoginRequest.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/dto/request/SignUpRequest.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/entity/User.java
Labels: 우선순위 ⭐⭐, 백 🐻, 리팩터링 🔧

#231 jib 환경 변수 주입 (#230)
  .github/workflows/build-backend.yml
  .github/workflows/deploy-backend.yml
  backend/text-me/.gitignore
  backend/text-me/build.gradle
  backend/text-me/src/main/resources/application.yml
Labels: 백 🐻, 개발 🧑‍💻, 리팩터링 🔧

#232 확장자가 HEIC이 아닌 파일 중 일부 업로드 되지 않는 현상 해결(#216)
  backend/text-me/src/main/java/gifterz/textme/s3Proxy/S3Service.java
  backend/text-me/src/main/resources/application.yml
Labels: 버그 🕷, 우선순위 ⭐⭐, 백 🐻, 리팩터링 🔧

#233 NotificationController가 text/event-stream을 반환하도록 명시 (#168)
  backend/text-me/src/main/java/gifterz/textme/domain/notification/NotificationController.java
Labels: 백 🐻, 개발 🧑‍💻, 리팩터링 🔧

#235 [v1.0.5] text-me 배포
  .github/workflows/build-backend.yml
  backend/text-me/build.gradle
  backend/text-me/src/main/java/gifterz/textme/domain/notification/NotificationController.java
  backend/text-me/src/main/java/gifterz/textme/s3Proxy/S3Service.java
  backend/text-me/src/main/resources/application.yml
Labels: 프론트 🐻‍❄️, 백 🐻

#237 이미지 업로드 최대 길이 제한(#236)
  frontend/pages/[uid]/write/select-card-picture.tsx
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#238 사진 사이즈 조절(#236)
  frontend/pages/[uid]/write/select-card-picture.tsx
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#241 눈 내리는 효과 추가(#240)
  frontend/.yarn/cache/react-snowfall-npm-1.2.1-ffb69bac7b-297ca98466.zip
  frontend/package.json
  frontend/pages/[uid]/index.tsx
  frontend/yarn.lock
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#244 비밀번호 최소 길이 수정(#243)
  frontend/pages/signin.tsx
Labels: 프론트 🐻‍❄️, 개발 🧑‍💻

#250 subscribe 컨트롤러 메서드가 JWT를 받도록 수정 (#168)
  backend/text-me/src/main/java/gifterz/textme/domain/notification/NotificationController.java
  backend/text-me/src/main/java/gifterz/textme/domain/notification/NotificationService.java
Labels: 버그 🕷, 백 🐻

#251 SSE 연결 추가 (#168)
  backend/text-me/src/main/java/gifterz/textme/domain/notification/NotificationService.java
Labels: 버그 🕷, 백 🐻
