Repository GIFTERZ/2023-text-me, pull requests merged in 2024-01, with the labels that each got.

#287 feat: 뒤로가기 버튼 추가
  frontend/components/slow/AddressForm.tsx
  frontend/components/slow/EmailForm.tsx
  frontend/components/slow/PostCodeForm.tsx
  frontend/components/slow/SelectMethod.tsx
  frontend/pages/slow-letter/get-info.tsx
Labels: 버그 🕷, 개발 🧑‍💻

#291 배경 오버플로우 해결 (#290)
  frontend/components/slow/AddressForm.tsx
  frontend/components/slow/EmailForm.tsx
  frontend/components/slow/PostCodeForm.tsx
  frontend/components/slow/SelectMethod.tsx
  frontend/components/write/SelectCard.tsx
  frontend/pages/slow-letter/get-info.tsx
  frontend/pages/slow-letter/index.tsx
  frontend/public/static/images/card-alt.ts
  frontend/stores/useCardPicture.ts
Labels: 버그 🕷

#293 Refactor: 느린 편지 보내기 api 추가
  backend/text-me/src/main/java/gifterz/textme/domain/letter/controller/LetterController.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/dto/request/ReceiverInfo.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/dto/request/SenderInfo.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/dto/request/SlowLetterWithAddressRequest.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/dto/request/SlowLetterWithEmailRequest.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/dto/response/SlowLetterWithAddressResponse.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/dto/response/SlowLetterWithEmailResponse.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/entity/SlowLetter.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/service/LetterService.java
Labels: 백 🐻, 개발 🧑‍💻, 리팩터링 🔧

#295 Refactor: Resolve email duplication between social and password login
  backend/text-me/src/main/java/gifterz/textme/domain/oauth/kakao/service/KakaoMemberClient.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/entity/User.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/service/UserService.java
Labels: 백 🐻, 개발 🧑‍💻, 리팩터링 🔧

#296 3D 회전 카드 구현
  frontend/components/slow/CardRotator.tsx
  frontend/components/slow/WriteFinishBox.tsx
  frontend/package.json
  frontend/pages/[uid]/write/select-card-picture.tsx
  frontend/pages/slow-letter/finish.tsx
  frontend/yarn.lock
Labels: 개발 🧑‍💻

#299 Refactor: send slow letter with address 요구사항 변경
  backend/text-me/src/main/java/gifterz/textme/domain/letter/controller/LetterController.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/dto/request/ReceiverInfo.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/dto/request/SenderInfo.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/dto/request/SlowLetterWithAddressRequest.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/dto/request/SlowLetterWithEmailRequest.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/dto/response/SlowLetterWithAddressResponse.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/entity/SlowLetter.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/service/LetterService.java
Labels: 백 🐻, 개발 🧑‍💻, 리팩터링 🔧

#300 느린 편지 주소로 보내기 API body 추가
  frontend/components/slow/AddressFormContext.ts
  frontend/pages/slow-letter/write.tsx
  frontend/stores/useSendSlowLetterByAddress.ts
  frontend/stores/useSlowLetterInfo.ts
Labels: 개발 🧑‍💻

#302 Refactor: change data type
  backend/text-me/src/main/java/gifterz/textme/domain/card/entity/Card.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/entity/Letter.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/entity/SlowLetter.java
  backend/text-me/src/main/java/gifterz/textme/domain/security/entity/RefreshToken.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/entity/Member.java
Labels: 백 🐻, 리팩터링 🔧

#306 Refactor: 엔티티 데이터 크기 변경
  backend/text-me/src/main/java/gifterz/textme/domain/card/entity/Card.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/entity/Letter.java
  backend/text-me/src/main/java/gifterz/textme/domain/letter/entity/SlowLetter.java
  backend/text-me/src/main/java/gifterz/textme/domain/security/entity/RefreshToken.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/entity/Member.java
Labels: 백 🐻, 리팩터링 🔧

#305 Refresh Token Rotation 개발 (#304)
  frontend/auth/refreshTokenRotation.ts
  frontend/auth/utils.ts
  frontend/mocks/data/refreshToken.js
  frontend/mocks/handlers/refreshToken.js
  frontend/pages/api/refresh.ts
  frontend/pages/api/test.ts
  frontend/pages/refreshtokentest.tsx
Labels: 프론트 🐻‍❄️, 리팩터링 🔧

#309 Refactor: refresh token
  backend/text-me/src/main/java/gifterz/textme/domain/oauth/service/OauthService.java
  backend/text-me/src/main/java/gifterz/textme/domain/security/entity/RefreshToken.java
  backend/text-me/src/main/java/gifterz/textme/domain/security/jwt/AuthTokenFilter.java
  backend/text-me/src/main/java/gifterz/textme/domain/security/jwt/JwtUtils.java
  backend/text-me/src/main/java/gifterz/textme/domain/security/repository/RefreshTokenRepository.java
  backend/text-me/src/main/java/gifterz/textme/domain/security/service/RefreshTokenService.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/controller/UserController.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/dto/request/TokenRefreshRequest.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/service/UserService.java
Labels: 백 🐻, 리팩터링 🔧

#310 refactor: password 길이 변경
  backend/text-me/src/main/java/gifterz/textme/domain/user/entity/Member.java
Labels: 백 🐻, 리팩터링 🔧

#311 Refactor: refresh token
  backend/text-me/src/main/java/gifterz/textme/domain/oauth/service/OauthService.java
  backend/text-me/src/main/java/gifterz/textme/domain/security/entity/RefreshToken.java
  backend/text-me/src/main/java/gifterz/textme/domain/security/jwt/JwtUtils.java
  backend/text-me/src/main/java/gifterz/textme/domain/security/repository/RefreshTokenRepository.java
  backend/text-me/src/main/java/gifterz/textme/domain/security/service/RefreshTokenService.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/dto/request/LoginRequest.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/dto/response/LoginResponse.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/dto/response/TokenRefreshResponse.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/dto/response/TokenResponse.java
  backend/text-me/src/main/java/gifterz/textme/domain/user/service/UserService.java
Labels: 백 🐻, 리팩터링 🔧

#314 refactor: 토큰 생성 및 리프레쉬 로직 @Transactional 추가
  backend/text-me/src/main/java/gifterz/textme/domain/security/service/RefreshTokenService.java
Labels: 백 🐻, 리팩터링 🔧

#316 RTR API 연동
  frontend/auth/Cookie.ts
  frontend/auth/api.ts
  frontend/auth/refresh.ts
  frontend/auth/refreshTokenRotation.ts
  frontend/auth/utils.ts
  frontend/components/signin/KakaoLoginButton.tsx
  frontend/constants/token.ts
  frontend/pages/index.tsx
  frontend/pages/refreshtokentest.tsx
  frontend/pages/signin.tsx
  frontend/stores/useKakaoLogin.ts
  frontend/stores/useLogin.ts
  frontend/stores/useMembers.ts
  frontend/stores/useSignup.ts
  frontend/styles/indicators/Loader.ts
Labels: 버그 🕷, 프론트 🐻‍❄️, 리팩터링 🔧

#322 Refactor: CI/CD 파이프라인 리팩터링
  .github/workflows/build-backend.yml
Labels: 개발 🧑‍💻
